name: "CodeQL"

on:
  push:
    branches: ["develop"]

defaults:
  run:
    working-directory: ./application/sample_csharp

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ["csharp"]

    steps:
      - name: Check Current Directory
        run: |
          pwd

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"

  Containerize:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          echo "$APPLICATIONDOCKERIMAGE"
          docker build -t "$APPLICATIONDOCKERIMAGE" .

      - name: Log in to Docker Hub or your container registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image
        run: docker push $APPLICATIONDOCKERIMAGE
