name: "CodeQL and Docker"

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./application/sample_csharp

jobs:
  analyze:
    name: Analyze CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["csharp"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"

      - name: Save CodeQL results
        uses: actions/upload-artifact@v2
        with:
          name: codeql-results
          path: ./codeql-results

  containerize:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    needs: analyze

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ env.APP_IMAGE }}:$GITHUB_SHA

      - name: Log in to Docker Hub or your container registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image
        run: docker push ${{ env.APP_IMAGE }}:$GITHUB_SHA
